# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7a5e59306ba213c2a31e2bc51004257cfaa06ec0e02ec45b3a46b2e7f5394d564678efccfde29485cb24d8685930c2e512463c49623c144905466f8d58b1cb

test:
  secret_key_base: e38080654215678cfeb224d63e47d3610c813c1dbe38861eb0e5097d6ec81ed103c3a4fcc8c4e577bdd8afe8c306a9a627a79e1110f8f85f2075734aa1b15524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
